### ISSUE TITLE
Where to put static files?

### ISSUE THREAD

**Issue by lakuapik** [hilmanski/mini-SSG#1]
Thanks for your simple yet cool sgg generator.

I dont have a clue on how to use static files in minissg. Is this feature exists or still in development?
One thing i notice is when we put static files in public folder, on every build, it will get removed.

**Comment by hilmanski** [comment]
Thank you @lakuapik 
Here is the site on how to install and where put your files.
[mini ssg website](https://minissg.vercel.app/install)

Take a look at point nr. 3a,
Your static files live in dev/pages/
example: dev/pages/index.html or dev/pages/about.html , etc..

Scroll through the bottom of that link, you'll find the general folder structure

Let me know if something not clear

**Comment by lakuapik** [comment]
Thanks @hilmanski

I thought the dev/pages folder just for html files only. 

IMHO, would it be better if there is dedicated folder to store static files (css/js/img) rather than put into dev/pages folder?

**Comment by hilmanski** [comment]
I've seen some SSG put their "static files" in separate folder.
At first I did separate assets folder and pages , but after some consideration, I bring them back together.

Mini SSG is different from typical SSG, where they have 'dynamic' and 'static' sites, 
Mini SSG is currently focusing on simplicity to prevent your write DRY HTML files (not to write dynamic content like blog), that's the reason I make a same entry location.

Thanks for your input. It might be change in the future.
BTW, have you tried it, how was your experience?

**Comment by hilmanski** [comment]
Hi @lakuapik 
I did change the folder structure today, with [version >= 0.2 of mini SSG](url)
all static folder and files move/live in '/dev/static' folder.

So if you have any css, js, sitemap.xml etc... you can put it there.
thanks for your input
